GET {{baseUrl}}/blogs
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/blogs
content-type: application/json
Authorization: Bearer {{token}}

{ 
  "title": "1984",
  "author": "george orwell",
  "url": "not provided"
}

###
POST {{baseUrl}}/blogs
content-type: application/json
Authorization: Bearer {{token}}

{ 
  "title": "animal farm",
  "author": "george orwell",
  "url": "test.com"
}

###
POST {{baseUrl}}/blogs
content-type: application/json
Authorization: Bearer {{token}}

{ 
  "title": "test",
  "author": "lesson",
  "url": "not provided"
}

###
GET {{baseUrl}}/blogs/6
Authorization: Bearer {{token}}


###
PUT {{baseUrl}}/blogs/1
content-type: application/json
Authorization: Bearer {{token}}

{ 
  "title": "the body",
  "author": "brayan",
  "url": "test.com"
}