GET {{baseUrl}}/users
Authorization: Bearer {{token}}



###
POST {{baseUrl}}/users
content-type: application/json
Authorization: Bearer {{token}}

{
    "username": "root two",
    "name": "Supermanuser",
    "password": "salainen"
}

###
POST {{baseUrl}}/users
content-type: application/json
Authorization: Bearer {{token}}

{
    "username": "yisacc",
    "name": "Yisacc Aberham",
    "password": "mytest"
}

###
POST {{baseUrl}}/users
content-type: application/json

{
    "username": "kasahun",
    "name": "kasahun Jote",
    "password": "kasthegreat"
}

###
POST {{baseUrl}}/users
content-type: application/json

{
    "username": "sara",
    "name": "sara seid",
    "password": "sariti"
}

###
GET {{baseUrl}}/users/3
Authorization: Bearer {{token}}


###
PUT {{baseUrl}}/users/8
content-type: application/json

{
    "username": "jasri",
    "name": "jasri seid"
}


###
POST {{baseUrl}}/users
content-type: application/json

{
    "username": "newuser",
    "name": "new user",
    "password": "testpass"
}